### ISSUE TITLE
Будет ли версия для Firefox?

### ISSUE THREAD

**Issue by deevroman** [Chimildic/YaMuTools#10]

**Comment by Chimildic** [comment]
Новая попытка пройти модерацию прошла успешно. Доступно по [ссылке](https://addons.mozilla.org/ru/firefox/addon/yamutools/). 
Возможны баги, не все проверил.

**Comment by karmicdude** [comment]
@Chimildic А можно версию обновить для Firefox или инструкцию как собрать под FF?

**Comment by Chimildic** [comment]
@karmicdude обновил.
