### ISSUE TITLE
А что произошло с версией для firefox?

### ISSUE THREAD

**Issue by darthsalakh** [Chimildic/YaMuTools#100]
Хотелось бы узнать вернется ли версия для firefox

**Comment by Chimildic** [comment]
Версия для Firefox скрыта из магазина из-за невозможности поддерживать ее в актуальном состоянии. Последняя доступная версия есть в [релизах](https://github.com/Chimildic/YaMuTools/releases). Ее можно установить в режиме разработчика. Некоторые функции в ней не работают. Например, сервис с обложками перестал работать с Россией, а плейлисты из ластфм нельзя импортирвать из-за [решения Яндекса](https://yandexmusic.userecho.com/communities/6/topics/10680-vernite-staryij-import-muzyiki-v-tekstovom-formate).
Возможно когда-нибудь вернусь к поддержке расширения, но не в ближайшее время.

**Comment by kaizenblumenblupper** [comment]
@Chimildic приветствую! Никак не получается установить на FF 134 расширение, пишет "это дополнение не может быть установлено, так как по-видимому повреждено".
Как быть?
