### ISSUE TITLE
Refused to load image

### ISSUE THREAD

**Issue by vlalog** [Chimildic/YaMuTools#2]
![image](https://user-images.githubusercontent.com/56760680/107853963-d4553300-6e29-11eb-873f-1fe2dc21724a.png)

**Comment by vlalog** [comment]
Версия 0.6.15

**Comment by Chimildic** [comment]
Похоже, это ошибки не от расширения. В логе нет ссылки на строчку кода. И воспроизвести не получается. 

На последнем Chrome случайная обложка загружается без ошибок.

**Comment by vlalog** [comment]
Не отрицаю.

Скорее всего, проблема местоположения - Крым

**Comment by vlalog** [comment]
Но проблема в том, что без обложки плейлист не создается

**Comment by Chimildic** [comment]
Попробуйте отключить настройку расширения "Случайная обложка"
