### ISSUE TITLE
Не находит очевидные дубликаты

### ISSUE THREAD

**Issue by filadog** [Chimildic/YaMuTools#83]
Доброго дня, спасибо за крутой инструмент!
У меня проблема с тем что в моем плейлисте не находятся дубликаты треков. 

![Web capture_6-4-2023_0458_music yandex ru](https://user-images.githubusercontent.com/51026900/230219212-9a1c18fe-83b0-40e3-9618-452c9386b885.jpeg)

На скриншоте 3 копии "$WERVE - CITY LIGHT$", копии идентичны (загрузил вручную)

**Comment by EldarAliev** [comment]
Добрый день!
Может потому что у этих "одинаковых" треков получился разный ID?
Посмотрите ссылку на треки, они должны быть вида https://music.yandex.ru/album/11111/track/2222

**Comment by filadog** [comment]
@EldarAliev так и есть, спасибо. Я думал, что треки сравниваются на уровне названий, а не по Id.
